server:
  port: 8080

spring:
  application:
    name: sf
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mes_dev
    username: postgres
    password: root

sf:
  entry:
    factoryId: 1000